# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'utility.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys,res_utility
from pythonProject.projectmain.sliderpage.slider import SecondWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1231, 836)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, -20, 1251, 841))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.setStyleSheet("border: none;")

        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(200, 20, 791, 121))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label = QtWidgets.QLabel(self.frame_8)
        self.label.setGeometry(QtCore.QRect(400, 20, 371, 81))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_7 = QtWidgets.QFrame(self.frame_8)
        self.frame_7.setGeometry(QtCore.QRect(280, 10, 101, 101))
        self.frame_7.setStyleSheet("image: url(:/utility/utility_logo.png);\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(110, 280, 1081, 91))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(110, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.frame_13 = QtWidgets.QFrame(self.frame_3)
        self.frame_13.setGeometry(QtCore.QRect(240, 0, 841, 91))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_21 = QtWidgets.QLabel(self.frame_13)
        self.label_21.setGeometry(QtCore.QRect(30, 10, 831, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_13)
        self.label_22.setGeometry(QtCore.QRect(30, 40, 831, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.push_utility_2 = QtWidgets.QPushButton(self.frame_3)
        self.push_utility_2.setGeometry(QtCore.QRect(10, 10, 91, 71))
        self.push_utility_2.setStyleSheet("\n"
"border: none")
        self.push_utility_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/utility/file_m_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_utility_2.setIcon(icon)
        self.push_utility_2.setIconSize(QtCore.QSize(100, 200))
        self.push_utility_2.setObjectName("push_utility_2")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(110, 160, 1081, 91))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(110, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.frame_14 = QtWidgets.QFrame(self.frame_4)
        self.frame_14.setGeometry(QtCore.QRect(240, 0, 841, 91))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_23 = QtWidgets.QLabel(self.frame_14)
        self.label_23.setGeometry(QtCore.QRect(30, 10, 831, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_14)
        self.label_24.setGeometry(QtCore.QRect(30, 40, 831, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.push_utility_1 = QtWidgets.QPushButton(self.frame_4)
        self.push_utility_1.setGeometry(QtCore.QRect(10, 10, 91, 71))
        self.push_utility_1.setStyleSheet("\n"
"border: none")
        self.push_utility_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/utility/7_zip_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_utility_1.setIcon(icon1)
        self.push_utility_1.setIconSize(QtCore.QSize(90, 150))
        self.push_utility_1.setObjectName("push_utility_1")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setGeometry(QtCore.QRect(110, 520, 1081, 91))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_6 = QtWidgets.QLabel(self.frame_9)
        self.label_6.setGeometry(QtCore.QRect(110, 30, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.frame_15 = QtWidgets.QFrame(self.frame_9)
        self.frame_15.setGeometry(QtCore.QRect(240, 0, 841, 91))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_25 = QtWidgets.QLabel(self.frame_15)
        self.label_25.setGeometry(QtCore.QRect(30, 10, 831, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_15)
        self.label_26.setGeometry(QtCore.QRect(30, 40, 831, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.push_utility_4 = QtWidgets.QPushButton(self.frame_9)
        self.push_utility_4.setGeometry(QtCore.QRect(10, 10, 91, 71))
        self.push_utility_4.setStyleSheet("\n"
"border: none")
        self.push_utility_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/utility/vim_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_utility_4.setIcon(icon2)
        self.push_utility_4.setIconSize(QtCore.QSize(100, 80))
        self.push_utility_4.setObjectName("push_utility_4")
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setGeometry(QtCore.QRect(110, 400, 1081, 91))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        self.label_7.setGeometry(QtCore.QRect(110, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.frame_16 = QtWidgets.QFrame(self.frame_10)
        self.frame_16.setGeometry(QtCore.QRect(240, 0, 841, 91))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_27 = QtWidgets.QLabel(self.frame_16)
        self.label_27.setGeometry(QtCore.QRect(30, 10, 831, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_16)
        self.label_28.setGeometry(QtCore.QRect(30, 40, 831, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.push_utility_3 = QtWidgets.QPushButton(self.frame_10)
        self.push_utility_3.setGeometry(QtCore.QRect(10, 10, 91, 71))
        self.push_utility_3.setStyleSheet("\n"
"border: none")
        self.push_utility_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/utility/calculator_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_utility_3.setIcon(icon3)
        self.push_utility_3.setIconSize(QtCore.QSize(90, 80))
        self.push_utility_3.setObjectName("push_utility_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1231, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "UTILITY"))
        self.label_4.setText(_translate("MainWindow", "File Mang."))
        self.label_21.setText(_translate("MainWindow", "A software tool for organizing, navigating, and managing files and folders on a computer system efficiently"))
        self.label_22.setText(_translate("MainWindow", "and intuitively."))
        self.label_5.setText(_translate("MainWindow", "Archive M."))
        self.label_23.setText(_translate("MainWindow", "Simplifies file compression and extraction tasks with an intuitive interface, supporting popular archive "))
        self.label_24.setText(_translate("MainWindow", "formats for seamless file management."))
        self.label_6.setText(_translate("MainWindow", "G Vim"))
        self.label_25.setText(_translate("MainWindow", "A powerful, highly configurable text editor with extensive plugin support, modal editing, and efficient"))
        self.label_26.setText(_translate("MainWindow", "keyboard-centric navigation for programmers."))
        self.label_7.setText(_translate("MainWindow", "Calculator"))
        self.label_27.setText(_translate("MainWindow", "A digital tool for mathematical computations, featuring basic arithmetic functions and sometimes"))
        self.label_28.setText(_translate("MainWindow", "advanced operations like trigonometry or logarithms."))

        self.push_utility_1.clicked.connect(self.File)
        self.push_utility_2.clicked.connect(self.Archive)
        self.push_utility_3.clicked.connect(self.Calculator)
        self.push_utility_4.clicked.connect(self.Vim)


    def File(self):
        label_text = "File Mang."
        label_disc = "A software tool for organizing, navigating, and managing files and folders on a computer system efficiently and intuitively."
        label_image = "/home/TEFLX/PycharmProjects/pythonProject/projectmain/Utility/7_zip_logo.png"
        soft_weight = 6
        self.open_slider(label_text, label_disc, label_image,soft_weight)

    def Archive(self):
        label_text = "Archive M."
        label_disc = "A software tool for organizing, navigating, and managing files and folders on a computer system efficiently formats for seamless file management."
        label_image = "/home/TEFLX/PycharmProjects/pythonProject/projectmain/Utility/file_m_logo.png"
        soft_weight = 7
        self.open_slider(label_text, label_disc, label_image,soft_weight)

    def Calculator(self):
        label_text = "Calculator"
        label_disc = "A digital tool for mathematical computations, featuring basic arithmetic functions and sometimes advanced operations like trigonometry or logarithms."
        label_image = "/home/TEFLX/PycharmProjects/pythonProject/projectmain/Utility/calculator_logo.png"
        soft_weight = 8
        self.open_slider(label_text, label_disc, label_image,soft_weight)

    def Vim(self):
        label_text = "G Vim"
        label_disc = "A powerful, highly configurable text editor with extensive plugin support, modal editing, and efficient keyboard-centric navigation for programmers. "
        label_image = "/home/TEFLX/PycharmProjects/pythonProject/projectmain/Utility/vim_logo.png"
        soft_weight = 9
        self.open_slider(label_text, label_disc, label_image,soft_weight)



    def open_slider(self, label_text, label_disc, label_image,soft_weight):
        self.second_window = SecondWindow(parent=self.centralwidget, label_text=label_text, label_disc=label_disc,
                                          label_image=label_image,soft_weight=soft_weight)
        self.second_window.setWindowModality(QtCore.Qt.ApplicationModal)
        self.second_window.show()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
