# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Productivity.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys,res_productivity
from pythonProject.projectmain.sliderpage.slider import SecondWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1258, 880)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-30, -10, 1251, 841))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.setStyleSheet("border: none;")

        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(200, 20, 891, 121))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label = QtWidgets.QLabel(self.frame_8)
        self.label.setGeometry(QtCore.QRect(340, 20, 501, 81))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_7 = QtWidgets.QFrame(self.frame_8)
        self.frame_7.setGeometry(QtCore.QRect(220, 10, 101, 101))
        self.frame_7.setStyleSheet("image: url(:/product/Productivity_logo.png);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(90, 170, 1081, 91))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(110, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.frame_14 = QtWidgets.QFrame(self.frame_4)
        self.frame_14.setGeometry(QtCore.QRect(240, 0, 841, 91))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_23 = QtWidgets.QLabel(self.frame_14)
        self.label_23.setGeometry(QtCore.QRect(30, 10, 831, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_14)
        self.label_24.setGeometry(QtCore.QRect(30, 40, 831, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.push_productivity_1 = QtWidgets.QPushButton(self.frame_4)
        self.push_productivity_1.setGeometry(QtCore.QRect(10, 10, 91, 71))
        self.push_productivity_1.setStyleSheet("\n"
"border: none")
        self.push_productivity_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/product/ms_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_productivity_1.setIcon(icon)
        self.push_productivity_1.setIconSize(QtCore.QSize(100, 150))
        self.push_productivity_1.setObjectName("push_productivity_1")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(90, 290, 1081, 91))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setGeometry(QtCore.QRect(110, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.frame_15 = QtWidgets.QFrame(self.frame_6)
        self.frame_15.setGeometry(QtCore.QRect(240, 0, 841, 91))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_25 = QtWidgets.QLabel(self.frame_15)
        self.label_25.setGeometry(QtCore.QRect(30, 10, 831, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_15)
        self.label_26.setGeometry(QtCore.QRect(30, 40, 831, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.push_productivity_2 = QtWidgets.QPushButton(self.frame_6)
        self.push_productivity_2.setGeometry(QtCore.QRect(10, 10, 91, 71))
        self.push_productivity_2.setStyleSheet("\n"
"border: none")
        self.push_productivity_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/product/libre_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_productivity_2.setIcon(icon1)
        self.push_productivity_2.setIconSize(QtCore.QSize(100, 200))
        self.push_productivity_2.setObjectName("push_productivity_2")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setGeometry(QtCore.QRect(90, 410, 1081, 91))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_10 = QtWidgets.QLabel(self.frame_9)
        self.label_10.setGeometry(QtCore.QRect(110, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.frame_16 = QtWidgets.QFrame(self.frame_9)
        self.frame_16.setGeometry(QtCore.QRect(240, 0, 841, 91))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_27 = QtWidgets.QLabel(self.frame_16)
        self.label_27.setGeometry(QtCore.QRect(30, 10, 831, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_16)
        self.label_28.setGeometry(QtCore.QRect(30, 40, 831, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.push_productivity_3 = QtWidgets.QPushButton(self.frame_9)
        self.push_productivity_3.setGeometry(QtCore.QRect(10, 10, 91, 71))
        self.push_productivity_3.setStyleSheet("\n"
"border: none")
        self.push_productivity_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/product/wine_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_productivity_3.setIcon(icon2)
        self.push_productivity_3.setIconSize(QtCore.QSize(100, 120))
        self.push_productivity_3.setObjectName("push_productivity_3")
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setGeometry(QtCore.QRect(90, 530, 1081, 91))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_11 = QtWidgets.QLabel(self.frame_10)
        self.label_11.setGeometry(QtCore.QRect(110, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.frame_17 = QtWidgets.QFrame(self.frame_10)
        self.frame_17.setGeometry(QtCore.QRect(240, 0, 841, 91))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label_29 = QtWidgets.QLabel(self.frame_17)
        self.label_29.setGeometry(QtCore.QRect(30, 10, 831, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_17)
        self.label_30.setGeometry(QtCore.QRect(30, 40, 831, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.push_productivity_4 = QtWidgets.QPushButton(self.frame_10)
        self.push_productivity_4.setGeometry(QtCore.QRect(10, 10, 91, 71))
        self.push_productivity_4.setStyleSheet("\n"
"border: none")
        self.push_productivity_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/product/qt_logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_productivity_4.setIcon(icon3)
        self.push_productivity_4.setIconSize(QtCore.QSize(100, 110))
        self.push_productivity_4.setObjectName("push_productivity_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1258, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PRODUCTIVITY"))
        self.label_6.setText(_translate("MainWindow", "Ms Office"))
        self.label_23.setText(_translate("MainWindow", "A suite of productivity software including Word, Excel, PowerPoint, and Outlook, facilitating document creation, data "))
        self.label_24.setText(_translate("MainWindow", "analysis, presentations, and communication."))
        self.label_7.setText(_translate("MainWindow", "Libre Off."))
        self.label_25.setText(_translate("MainWindow", "A free, open-source office suite offering word processing, spreadsheets, presentations, and more, compatible"))
        self.label_26.setText(_translate("MainWindow", "with popular document formats."))
        self.label_10.setText(_translate("MainWindow", "Wine "))
        self.label_27.setText(_translate("MainWindow", "Software enabling Windows applications to run on Linux and macOS systems, fostering compatibility across "))
        self.label_28.setText(_translate("MainWindow", "different operating platforms."))
        self.label_11.setText(_translate("MainWindow", "QT"))
        self.label_29.setText(_translate("MainWindow", "A graphical user interface design tool for creating Qt-based applications efficiently through drag-and-drop "))
        self.label_30.setText(_translate("MainWindow", "interface design."))

        self.push_productivity_1.clicked.connect(self.ms_office)
        self.push_productivity_2.clicked.connect(self.Libre_Off)
        self.push_productivity_3.clicked.connect(self.Wine)
        self.push_productivity_4.clicked.connect(self.QT)


    def ms_office(self):
        label_text = "MS_office"
        label_disc = "A suite of productivity software including Word, Excel, PowerPoint, and Outlook, facilitating document creation, data analysis, presentations, and communication."
        label_image = "/home/TEFLX/PycharmProjects/pythonProject/projectmain/Productivity/ms_logo.png"
        soft_weight= 18
        self.open_slider(label_text, label_disc, label_image,soft_weight)

    def Libre_Off(self):
        label_text = "Libre Off"
        label_disc = "A free, open-source office suite offering word processing, spreadsheets, presentations, and more, compatible with popular document formats."
        label_image = "/home/TEFLX/PycharmProjects/pythonProject/projectmain/Productivity/libre_logo.png"
        soft_weight= 19
        self.open_slider(label_text, label_disc, label_image,soft_weight)

    def Wine (self):
        label_text = "Wine"
        label_disc = "Software enabling Windows applications to run on Linux and macOS systems, fostering compatibility across different operating platforms."
        label_image = "/home/TEFLX/PycharmProjects/pythonProject/projectmain/Productivity/wine_logo.png"
        soft_weight= 20
        self.open_slider(label_text, label_disc, label_image,soft_weight)

    def QT(self):
        label_text = "QT"
        label_disc = "A graphical user interface design tool for creating Qt-based applications efficiently through drag-and-drop interface design. "
        label_image = "/home/TEFLX/PycharmProjects/pythonProject/projectmain/Productivity/qt_logo.jpg"
        soft_weight= 21
        self.open_slider(label_text, label_disc, label_image,soft_weight)


    def open_slider(self, label_text, label_disc, label_image,soft_weight):
        self.second_window = SecondWindow(parent=self.centralwidget, label_text=label_text, label_disc=label_disc,
                                          label_image=label_image)
        self.second_window.setWindowModality(QtCore.Qt.ApplicationModal,soft_weight=soft_weight)
        self.second_window.show()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

