# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tools.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys,res_tools
from pythonProject.projectmain.sliderpage.slider import SecondWindow

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1258, 1291)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-30, 0, 1251, 841))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.setStyleSheet("border: none;")

        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(110, 160, 1081, 91))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.push_tools_1 = QtWidgets.QPushButton(self.frame_2)
        self.push_tools_1.setGeometry(QtCore.QRect(0, 10, 91, 71))
        self.push_tools_1.setStyleSheet("\n"
"border: none")
        self.push_tools_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/tools/meta_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_tools_1.setIcon(icon)
        self.push_tools_1.setIconSize(QtCore.QSize(100, 150))
        self.push_tools_1.setObjectName("push_tools_1")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(110, 30, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(270, 10, 791, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(270, 50, 711, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(240, 20, 791, 121))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label = QtWidgets.QLabel(self.frame_8)
        self.label.setGeometry(QtCore.QRect(380, 20, 391, 81))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_7 = QtWidgets.QFrame(self.frame_8)
        self.frame_7.setGeometry(QtCore.QRect(270, 10, 101, 101))
        self.frame_7.setStyleSheet("image: url(:/tools/graphics_logo.png);\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(110, 390, 1081, 91))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setGeometry(QtCore.QRect(110, 30, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_6)
        self.label_11.setGeometry(QtCore.QRect(270, 10, 791, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.frame_6)
        self.label_13.setGeometry(QtCore.QRect(270, 50, 711, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.push_tools_3 = QtWidgets.QPushButton(self.frame_6)
        self.push_tools_3.setGeometry(QtCore.QRect(10, 10, 91, 71))
        self.push_tools_3.setStyleSheet("\n"
"border: none")
        self.push_tools_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/tools/mysql_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_tools_3.setIcon(icon1)
        self.push_tools_3.setIconSize(QtCore.QSize(100, 200))
        self.push_tools_3.setObjectName("push_tools_3")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setGeometry(QtCore.QRect(110, 280, 1081, 91))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_14 = QtWidgets.QLabel(self.frame_9)
        self.label_14.setGeometry(QtCore.QRect(110, 30, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_9)
        self.label_15.setGeometry(QtCore.QRect(270, 10, 791, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_9)
        self.label_16.setGeometry(QtCore.QRect(270, 50, 711, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.push_tools_2 = QtWidgets.QPushButton(self.frame_9)
        self.push_tools_2.setGeometry(QtCore.QRect(10, 10, 91, 71))
        self.push_tools_2.setStyleSheet("\n"
"border: none")
        self.push_tools_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/tools/wireshark_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_tools_2.setIcon(icon2)
        self.push_tools_2.setIconSize(QtCore.QSize(100, 150))
        self.push_tools_2.setObjectName("push_tools_2")
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setGeometry(QtCore.QRect(110, 510, 1081, 91))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_17 = QtWidgets.QLabel(self.frame_10)
        self.label_17.setGeometry(QtCore.QRect(110, 30, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_10)
        self.label_18.setGeometry(QtCore.QRect(270, 10, 791, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_10)
        self.label_19.setGeometry(QtCore.QRect(270, 50, 711, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.push_tools_4 = QtWidgets.QPushButton(self.frame_10)
        self.push_tools_4.setGeometry(QtCore.QRect(10, 10, 91, 71))
        self.push_tools_4.setStyleSheet("\n"
"border: none")
        self.push_tools_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/tools/jupyter_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_tools_4.setIcon(icon3)
        self.push_tools_4.setIconSize(QtCore.QSize(90, 80))
        self.push_tools_4.setObjectName("push_tools_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1258, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Metasploit"))
        self.label_3.setText(_translate("MainWindow", "A powerful penetration testing framework for discovering, exploiting, and managing vulnerabilities, aiding "))
        self.label_12.setText(_translate("MainWindow", "in cybersecurity assessments and defense strategies."))
        self.label.setText(_translate("MainWindow", "TOOLS"))
        self.label_10.setText(_translate("MainWindow", "My Sql"))
        self.label_11.setText(_translate("MainWindow", "A popular open-source relational database management system, widely used for web applications, supporting "))
        self.label_13.setText(_translate("MainWindow", "data storage, retrieval, and management."))
        self.label_14.setText(_translate("MainWindow", "Wireshark"))
        self.label_15.setText(_translate("MainWindow", "A powerful network protocol analyzer offering real-time traffic inspection, packet capture, and comprehensive"))
        self.label_16.setText(_translate("MainWindow", "network troubleshooting tools for professionals."))
        self.label_17.setText(_translate("MainWindow", "Jupyter"))
        self.label_18.setText(_translate("MainWindow", "Interactive, web-based platform for creating and sharing documents containing live code, equations,"))
        self.label_19.setText(_translate("MainWindow", "visualizations and narrative text for data analysis."))
        self.push_tools_1.clicked.connect(self.Metasploit)
        self.push_tools_3.clicked.connect(self.MySql)
        self.push_tools_2.clicked.connect(self.Wireshark)
        self.push_tools_4.clicked.connect(self.Jupyter)


    def Metasploit(self):
        label_text = "Metasploit"
        label_disc = "A powerful penetration testing framework for discovering, exploiting, and managing vulnerabilities, aiding in cybersecurity assessments and defense strategies."
        label_image = "/home/TEFLX/PycharmProjects/pythonProject/projectmain/Tools/meta_logo.png"
        soft_weight= 14
        self.open_slider(label_text, label_disc, label_image,soft_weight)

    def MySql(self):
        label_text = "MySql"
        label_disc = "A popular open-source relational database management system, widely used for web applications, supporting data storage, retrieval, and management."
        label_image = "/home/TEFLX/PycharmProjects/pythonProject/projectmain/Tools/mysql_logo.png"
        soft_weight= 15
        self.open_slider(label_text, label_disc, label_image,soft_weight)

    def Wireshark(self):
        label_text = "Wireshark"
        label_disc = "A powerful network protocol analyzer offering real-time traffic inspection, packet capture, and comprehensive network troubleshooting tools for professionals."
        label_image = "wireshark_logo.png"
        soft_weight= 16
        self.open_slider(label_text, label_disc, label_image,soft_weight)

    def Jupyter(self):
        label_text = "Jupyter"
        label_disc = "Interactive, web-based platform for creating and sharing documents containing live code, equations,visualizations and narrative text for data analysis. "
        label_image = "/home/TEFLX/PycharmProjects/pythonProject/projectmain/Tools/jupyter_logo.png"
        soft_weight= 17
        self.open_slider(label_text, label_disc, label_image,soft_weight)


    def open_slider(self, label_text, label_disc, label_image):
        self.second_window = SecondWindow(parent=self.centralwidget, label_text=label_text, label_disc=label_disc,
                                          label_image=label_image,soft_weight=soft_weight)
        self.second_window.setWindowModality(QtCore.Qt.ApplicationModal)
        self.second_window.show()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
