from PyQt5 import QtCore, QtGui, QtWidgets, Qt
import sys, res_webscan, os
from pythonProject.projectmain.sliderpage.slider import SecondWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")

        MainWindow.resize(1258, 894)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1251, 841))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.setStyleSheet("border: none;")

        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(100, 520, 1081, 91))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.push_webscan_4 = QtWidgets.QPushButton(self.frame_2)
        self.push_webscan_4.setGeometry(QtCore.QRect(10, 10, 91, 71))
        self.push_webscan_4.setStyleSheet("\n"
                                          "border: none")
        self.push_webscan_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/websacn/brave_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_webscan_4.setIcon(icon)
        self.push_webscan_4.setIconSize(QtCore.QSize(100, 80))
        self.push_webscan_4.setObjectName("push_webscan_4")

        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(110, 30, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.frame_12 = QtWidgets.QFrame(self.frame_2)
        self.frame_12.setGeometry(QtCore.QRect(200, 0, 881, 91))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_19 = QtWidgets.QLabel(self.frame_12)
        self.label_19.setGeometry(QtCore.QRect(40, 10, 841, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_12)
        self.label_20.setGeometry(QtCore.QRect(40, 40, 821, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(100, 160, 1081, 91))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.push_webscan_1 = QtWidgets.QPushButton(self.frame_3)
        self.push_webscan_1.setGeometry(QtCore.QRect(10, 10, 91, 71))
        self.push_webscan_1.setStyleSheet("\n"
                                          "border: none")
        self.push_webscan_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/websacn/chrome_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_webscan_1.setIcon(icon1)
        self.push_webscan_1.setIconSize(QtCore.QSize(140, 90))
        self.push_webscan_1.setObjectName("push_webscan_1")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(110, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.frame_13 = QtWidgets.QFrame(self.frame_3)
        self.frame_13.setGeometry(QtCore.QRect(210, 0, 871, 91))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_21 = QtWidgets.QLabel(self.frame_13)
        self.label_21.setGeometry(QtCore.QRect(30, 10, 831, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_13)
        self.label_22.setGeometry(QtCore.QRect(30, 40, 831, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(100, 400, 1081, 91))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.push_webscan_3 = QtWidgets.QPushButton(self.frame_4)
        self.push_webscan_3.setGeometry(QtCore.QRect(10, 10, 91, 71))
        self.push_webscan_3.setStyleSheet("\n"
                                          "border: none")
        self.push_webscan_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/websacn/opera_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_webscan_3.setIcon(icon2)
        self.push_webscan_3.setIconSize(QtCore.QSize(100, 70))
        self.push_webscan_3.setObjectName("push_webscan_3")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(110, 30, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.frame_11 = QtWidgets.QFrame(self.frame_4)
        self.frame_11.setGeometry(QtCore.QRect(200, 0, 881, 91))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_17 = QtWidgets.QLabel(self.frame_11)
        self.label_17.setGeometry(QtCore.QRect(40, 10, 821, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_11)
        self.label_18.setGeometry(QtCore.QRect(40, 40, 821, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(100, 640, 1081, 91))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.push_webscan_5 = QtWidgets.QPushButton(self.frame_5)
        self.push_webscan_5.setGeometry(QtCore.QRect(10, 10, 91, 71))
        self.push_webscan_5.setStyleSheet("\n"
                                          "border: none")
        self.push_webscan_5.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/websacn/Tor_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_webscan_5.setIcon(icon3)
        self.push_webscan_5.setIconSize(QtCore.QSize(100, 70))
        self.push_webscan_5.setObjectName("push_webscan_5")
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        self.label_8.setGeometry(QtCore.QRect(110, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.frame_10 = QtWidgets.QFrame(self.frame_5)
        self.frame_10.setGeometry(QtCore.QRect(200, 0, 881, 91))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_15 = QtWidgets.QLabel(self.frame_10)
        self.label_15.setGeometry(QtCore.QRect(40, 10, 821, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_10)
        self.label_16.setGeometry(QtCore.QRect(40, 40, 821, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(100, 280, 1081, 91))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setGeometry(QtCore.QRect(110, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.push_webscan_2 = QtWidgets.QPushButton(self.frame_6)
        self.push_webscan_2.setGeometry(QtCore.QRect(10, 10, 81, 71))
        self.push_webscan_2.setStyleSheet("\n"
                                          "border: none")
        self.push_webscan_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/websacn/fire_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_webscan_2.setIcon(icon4)
        self.push_webscan_2.setIconSize(QtCore.QSize(100, 70))
        self.push_webscan_2.setObjectName("push_webscan_2")
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        self.frame_9.setGeometry(QtCore.QRect(200, 0, 881, 91))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_13 = QtWidgets.QLabel(self.frame_9)
        self.label_13.setGeometry(QtCore.QRect(40, 10, 841, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_9)
        self.label_14.setGeometry(QtCore.QRect(40, 40, 821, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(200, 20, 791, 121))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label = QtWidgets.QLabel(self.frame_8)
        self.label.setGeometry(QtCore.QRect(370, 20, 401, 81))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_7 = QtWidgets.QFrame(self.frame_8)
        self.frame_7.setGeometry(QtCore.QRect(260, 10, 101, 101))
        self.frame_7.setStyleSheet("image: url(:/websacn/webscan_logo.png);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1258, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Brave"))
        self.label_19.setText(_translate("MainWindow",
                                         "Privacy-focused, fast, and secure web browser with built-in ad-blocking and cryptocurrency rewards for"))
        self.label_20.setText(_translate("MainWindow", "users and content creators."))
        self.label_4.setText(_translate("MainWindow", "Chrome"))
        self.label_21.setText(_translate("MainWindow",
                                         " A fast, secure web browser by Google, offering extensions, synchronization across devices, and a user-friendly"))
        self.label_22.setText(_translate("MainWindow", " interface for browsing."))
        self.label_6.setText(_translate("MainWindow", "Opera"))
        self.label_17.setText(_translate("MainWindow",
                                         "A fast, secure web browser with built-in ad blocker, VPN, and customizable features for efficient browsing"))
        self.label_18.setText(_translate("MainWindow", "experiences."))
        self.label_8.setText(_translate("MainWindow", "Tor"))
        self.label_15.setText(_translate("MainWindow",
                                         "An open-source web browser emphasizing privacy and anonymity, utilizing the Tor network  to conceal users\'"))
        self.label_16.setText(_translate("MainWindow", "online activities."))
        self.label_10.setText(_translate("MainWindow", "Firefox"))
        self.label_13.setText(_translate("MainWindow",
                                         "A fast, secure, and customizable web browser with privacy features, extensions support, and cross-platform "))
        self.label_14.setText(_translate("MainWindow", "compatibility for seamless browsing."))
        self.label.setText(_translate("MainWindow", "WEB SCAN"))

        self.push_webscan_4.clicked.connect(self.brave)
        self.push_webscan_1.clicked.connect(self.chrome)
        self.push_webscan_3.clicked.connect(self.opera)
        self.push_webscan_2.clicked.connect(self.fire)
        self.push_webscan_5.clicked.connect(self.Tor)

    def brave(self):
        label_text = "Brave"
        label_disc = "Privacy-focused, fast, and secure web browser with built-in ad-blocking and cryptocurrency rewards for users and content creators."
        label_image = "/home/TEFLX/PycharmProjects/pythonProject/projectmain/WebScan/brave_logo.png"
        soft_weight = 1
        self.open_slider(label_text, label_disc, label_image,soft_weight)

    def chrome(self):
        label_text = "Chrome"
        label_disc = "A fast, secure web browser by Google, offering extensions, synchronization across devices, and a user-friendly interface for browsing."
        label_image = "/home/TEFLX/PycharmProjects/pythonProject/projectmain/WebScan/chrome_logo.png"
        soft_weight = 2
        self.open_slider(label_text, label_disc, label_image,soft_weight)

    def opera(self):
        label_text = "Opera"
        label_disc = "A fast, secure web browser with built-in ad blocker, VPN, and customizable features for efficient browsing"
        label_image = "/home/TEFLX/PycharmProjects/pythonProject/projectmain/WebScan/opera_logo.png"
        soft_weight = 3
        self.open_slider(label_text, label_disc, label_image,soft_weight)

    def fire(self):
        label_text = "FireFox"
        label_disc = "A fast, secure, and customizable web browser with privacy features, extensions support, and cross-platform compatibility for seamless browsing. "
        label_image = "/home/TEFLX/PycharmProjects/pythonProject/projectmain/WebScan/fire_logo.png"
        soft_weight = 4
        self.open_slider(label_text, label_disc, label_image,soft_weight)

    def Tor(self):
        label_text = "Tor"
        label_disc = "An open-source web browser emphasizing privacy and anonymity, utilizing the Tor network  to conceal users online activities."
        label_image = "/home/TEFLX/PycharmProjects/pythonProject/projectmain/WebScan/Tor_logo.png"
        soft_weight = 5
        self.open_slider(label_text, label_disc, label_image,soft_weight)

    def open_slider(self, label_text, label_disc, label_image,soft_weight):
        self.second_window = SecondWindow(parent=self.centralwidget, label_text=label_text, label_disc=label_disc,
                                          label_image=label_image,soft_weight=soft_weight)
        self.second_window.setWindowModality(QtCore.Qt.ApplicationModal)
        self.second_window.show()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
